sudo: required

services:
  - docker

script:
  - docker build -t hypothesis/smokey smokey/

after_success:
  # Tag with build number and deploy to docker hub if we're on master.
  - >
    test "$TRAVIS_PULL_REQUEST" = "false" &&
    test "$TRAVIS_BRANCH" = "master" &&
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    docker tag hypothesis/smokey hypothesis/smokey:"$TRAVIS_BUILD_NUMBER" &&
    docker push hypothesis/smokey
