#!/bin/sh
#
# Deploy built docker images from Travis to the Docker Hub.
#
# This script checks if we're building on the master branch in Travis. If so,
# then it will tag and push the changed images to Docker Hub.
#
# Images are tagged with the Travis build number

if [ "$TRAVIS" != "true" ]; then
    echo >&2 "This script is intended to be run on Travis CI! Aborting."
    exit 1
fi

set -eu

if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    echo >&2 "Not deploying from a pull request. Exiting."
    exit 0
fi

if [ "$TRAVIS_BRANCH" != "master" ]; then
    echo >&2 "Not deploying from a branch other than master. Exiting."
    exit 0
fi

# Tag an image with the specified tag and push it to the Docker Hub.
push_image () {
    local image=$1
    local tag=$2
    echo >&2 "Tagging ${image}:latest as ${image}:${tag}..."
    docker tag "$image" "$image":"$tag"
    echo >&2 "Pushing ${image} to Docker Hub..."
    docker push "$image"
}

# The DOCKER_* environment variables are secrets we need to have configured for
# the Travis project.
echo >&2 "Logging into Docker Hub..."
docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
push_image hypothesis/smokey "$TRAVIS_BUILD_NUMBER"
